Update Kyber to Round3
mupq/pqm3 pull request #8
Opened 2021-05-13 08:14 UTC by rugo

This PR addresses #5. 

The code is mainly taken from mupq/pqm4@a1cb9e2  mupq/pqm4@4975d4d (these are the commits mentioned in #5).
Only difference from the pqm4 version is the naming of assembly functions (`basemul_asm_m3` instead of `basemul_asm` etc.). 

The main change this introduces into pqm3 is that the file structure is now different.

Before this PR, Kyber768 and Kyber1024 implementation files were just symlinks to Kyber512. 
AFAICS this is not possible for Round 3 anymore. 

The new status is that:

* Kyber512 is an isolated implementation with own files
* Kyber768 is an isolated implementation with own files
* Kyber1024 implementation files are symlinks to Kyber768

It might be possible to share certain file between Kyber512 and Kyber768 via symlinks. 
I personally prefer the disjoint implementation files.

I ran the tests on the NUCLEO-F207ZG and they worked. Feel free to review, feedback or directly change.

![image](https://user-images.githubusercontent.com/9132874/118098108-c9cc1a80-b3d3-11eb-882a-9d0191b43b72.png)

2021-06-06 19:36 UTC, rpls commented
Please excuse the delay, was busy the the `mupq` stuff in general. Could you fix the references and rebase against the master?

2021-06-06 19:36 UTC, rpls requested changes
Please excuse the delay, was busy the the mupq stuff in general. Could you fix the references and rebase against the master?

2021-06-06 19:36 UTC, rpls commented on crypto_kem/kyber512/m3/poly.c
> -extern void asm_frommont_m3(int16_t *r);
This is wrong, the `asm_frommont_m3` reference appears to be the correct one.

2021-06-06 19:36 UTC, rpls commented on crypto_kem/kyber512/m3/poly.c
> -  asm_frommont_m3(r->coeffs);
Same here.

2021-06-29 19:03 UTC, rugo commented
Sorry for the delay.

You're absolutely right. I changed it to `asm_frommont_m3` and rebased.

2021-08-13 06:03 UTC, mkannwischer commented
Sorry for the super long delay. This looks good to me now. 
I rebased and ran the benchmarks. 
Thank you @rugo!

2021-08-13 06:03 UTC, merged